<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>amr_fleet_core</name>
  <version>0.1.0</version>
  <description>Core interface abstractions and state management for decentralized AMR fleet coordination.</description>
  <maintainer email="raghavgangrade72009@gmail.com">Raghav Gangrade</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>amr_fleet_msgs</depend>
  <depend>amr_fleet_sim</depend>
  <exec_depend>python3-psutil</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

